# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='shop.Tag'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default=1, help_text='제목을 입력해 주세요', max_length=100, verbose_name='식당명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='content',
            field=models.TextField(max_length=500, verbose_name='내용'),
        ),
    ]
